### ISSUE TITLE
Getting array values from properties that contain digits fails

### ISSUE THREAD

**Issue by egmacke** [justinlettau/ts-dot-prop#29]
## Describe the Issue

When trying to get nested values from an array, if the property names contain digits the library fails to resolve the values.

Example:

```typescript
const obj = [
  {
    prop1: 'nested1'
  },
  {
    prop1: 'nested2'
  }
]

get(obj, "prop1"); // undefined
```

## Expected behavior

In the example above:

`get(obj, "prop1")// ['nested1', 'nested2']`

## Solution

I believe the solution is to restrict the `indexer` RegExp to match _only_ digits rather than a string containing digits.

I will submit a PR for this fix.

**Comment by egmacke** [comment]
@justinlettau I've got a fix for this, but I can't push it to create a PR. Are you happy to give me access to push the fix?

**Comment by justinlettau** [comment]
@egmacke Feel free to [fork the repo](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo) and [create a pull request from the fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork). Thanks!
