### ISSUE TITLE
Improper support for infinitely nested objects in `_paths()` logic

### ISSUE THREAD

**Issue by jamie-bell** [justinlettau/ts-dot-prop#53]
## Describe the Issue

Issue manifests when you have an object containing an object and additional properties after said nested object.

## Expected behavior

Would expect all trees properly return with their nested prefixes

## Steps to Reproduce

```
const howToBreakIt = {
      something: false,
      someObject: { 
        someNestedObject: {
          someProperty: 1
        },
        someBoolean: false
      }
    };
```

Expected results are:
`['something', 'someObject.someNestedObject.someProperty', 'someObject.someBoolean']`

Current version produces:
`['something', 'someObject.someNestedObject.someProperty', 'someBoolean']`

## Other Information

I have a fix for this that I will PR in as 2.1.1 shortly. The issue is we are resetting the `lead` array instead of just popping off the last prefix in the chain.

```
lead = [];
```
needs to be
```
lead.pop();
```

**Comment by justinlettau** [comment]
Thanks @jamie-bell! Released in v2.1,1 ✅
