### ISSUE TITLE
NPM 2.1.1 does not contain the lead.pop() fix

### ISSUE THREAD

**Issue by jamie-bell** [justinlettau/ts-dot-prop#55]
## Describe the Issue

`npm install ts-dot-prop` does not produce the latest code

## Expected behavior

I expect the `lead.pop()` fix from the last PR merge to be included in the 2.1.1 npm distribution

## Steps to Reproduce

```
mkdir ts-dot-prop-test
cd ts-dot-prop-test
npm i ts-dot-prop
cd node_modules/dist/ts-dot-prop
```
^ witness in index.js that it still contains `lead = []`

## Other Information

I have attempted force clearing my npm cache to no avail. Not sure if there's anything else to try

**Comment by justinlettau** [comment]
Oops, sorry about that! Problem with the release script. Just released v2.1.2 and it should be included in there.
